const fs = require("fs");

fs.writeFileSync("src/components/templates/main-layout.tsx", "import React from \"react\";\nimport { Header } from \"../organisms/header\";\n\nexport type MainLayoutProps = { title: string; children: React.ReactNode; headerRight?: React.ReactNode; };\nexport const MainLayout = function(props: MainLayoutProps) { return (<div className=\"main-layout\"><Header title={props.title} right={props.headerRight} /><main className=\"main-layout__content\">{props.children}</main></div>); };");

fs.writeFileSync("src/components/templates/editor-layout.tsx", "import React from \"react\";\nimport { Header } from \"../organisms/header\";\nimport { Sidebar } from \"../organisms/sidebar\";\n\nexport type EditorLayoutProps = { title: string; headerRight?: React.ReactNode; sidebarTop?: React.ReactNode; sidebarBottom?: React.ReactNode; children: React.ReactNode; playbackBar?: React.ReactNode; };\nexport const EditorLayout = function(props: EditorLayoutProps) { return (<div className=\"editor-layout\"><Header title={props.title} right={props.headerRight} /><div className=\"editor-layout__body\"><Sidebar><div className=\"sidebar-top\">{props.sidebarTop}</div><div className=\"sidebar-bottom\">{props.sidebarBottom}</div></Sidebar><main className=\"editor-layout__main\">{props.children}{props.playbackBar && <div className=\"editor-layout__footer\">{props.playbackBar}</div>}</main></div></div>); };");

fs.writeFileSync("src/components/templates/settings-layout.tsx", "import React from \"react\";\nimport { Header } from \"../organisms/header\";\nimport { Sidebar } from \"../organisms/sidebar\";\n\nexport type SettingsLayoutProps = { title: string; navigation?: React.ReactNode; children: React.ReactNode; };\nexport const SettingsLayout = function(props: SettingsLayoutProps) { return (<div className=\"settings-layout\"><Header title={props.title} /><div className=\"settings-layout__body\"><Sidebar>{props.navigation}</Sidebar><main className=\"settings-layout__content\">{props.children}</main></div></div>); };");

fs.writeFileSync("src/components/templates/index.ts", "export * from \"./main-layout\";\nexport * from \"./editor-layout\";\nexport * from \"./settings-layout\";");
console.log("Done");
