export const MIDI_INSTRUMENTS = [
  { value: 'acoustic_grand_piano', label: '1. Acoustic Grand Piano' },
  { value: 'bright_acoustic_piano', label: '2. Bright Acoustic Piano' },
  { value: 'electric_grand_piano', label: '3. Electric Grand Piano' },
  { value: 'honkytonk_piano', label: '4. Honky-tonk Piano' },
  { value: 'electric_piano_1', label: '5. Electric Piano 1' },
  { value: 'electric_piano_2', label: '6. Electric Piano 2' },
  { value: 'harpsichord', label: '7. Harpsichord' },
  { value: 'clavinet', label: '8. Clavinet' },
  { value: 'celesta', label: '9. Celesta' },
  { value: 'glockenspiel', label: '10. Glockenspiel' },
  { value: 'music_box', label: '11. Music Box' },
  { value: 'vibraphone', label: '12. Vibraphone' },
  { value: 'marimba', label: '13. Marimba' },
  { value: 'xylophone', label: '14. Xylophone' },
  { value: 'tubular_bells', label: '15. Tubular Bells' },
  { value: 'dulcimer', label: '16. Dulcimer' },
  { value: 'drawbar_organ', label: '17. Drawbar Organ' },
  { value: 'percussive_organ', label: '18. Percussive Organ' },
  { value: 'rock_organ', label: '19. Rock Organ' },
  { value: 'church_organ', label: '20. Church Organ' },
  { value: 'reed_organ', label: '21. Reed Organ' },
  { value: 'accordion', label: '22. Accordion' },
  { value: 'harmonica', label: '23. Harmonica' },
  { value: 'tango_accordion', label: '24. Tango Accordion' },
  { value: 'acoustic_guitar_nylon', label: '25. Acoustic Guitar (nylon)' },
  { value: 'acoustic_guitar_steel', label: '26. Acoustic Guitar (steel)' },
  { value: 'electric_guitar_jazz', label: '27. Electric Guitar (jazz)' },
  { value: 'electric_guitar_clean', label: '28. Electric Guitar (clean)' },
  { value: 'electric_guitar_muted', label: '29. Electric Guitar (muted)' },
  { value: 'overdriven_guitar', label: '30. Overdriven Guitar' },
  { value: 'distortion_guitar', label: '31. Distortion Guitar' },
  { value: 'guitar_harmonics', label: '32. Guitar harmonics' },
  { value: 'acoustic_bass', label: '33. Acoustic Bass' },
  { value: 'electric_bass_finger', label: '34. Electric Bass (finger)' },
  { value: 'electric_bass_pick', label: '35. Electric Bass (pick)' },
  { value: 'fretless_bass', label: '36. Fretless Bass' },
  { value: 'slap_bass_1', label: '37. Slap Bass 1' },
  { value: 'slap_bass_2', label: '38. Slap Bass 2' },
  { value: 'synth_bass_1', label: '39. Synth Bass 1' },
  { value: 'synth_bass_2', label: '40. Synth Bass 2' },
  { value: 'violin', label: '41. Violin' },
  { value: 'viola', label: '42. Viola' },
  { value: 'cello', label: '43. Cello' },
  { value: 'contrabass', label: '44. Contrabass' },
  { value: 'tremolo_strings', label: '45. Tremolo Strings' },
  { value: 'pizzicato_strings', label: '46. Pizzicato Strings' },
  { value: 'orchestral_harp', label: '47. Orchestral Harp' },
  { value: 'timpani', label: '48. Timpani' },
  { value: 'string_ensemble_1', label: '49. String Ensemble 1' },
  { value: 'string_ensemble_2', label: '50. String Ensemble 2' },
  { value: 'synth_strings_1', label: '51. SynthStrings 1' },
  { value: 'synth_strings_2', label: '52. SynthStrings 2' },
  { value: 'choir_aahs', label: '53. Choir Aahs' },
  { value: 'voice_oohs', label: '54. Voice Oohs' },
  { value: 'synth_choir', label: '55. Synth Voice' },
  { value: 'orchestra_hit', label: '56. Orchestra Hit' },
  { value: 'trumpet', label: '57. Trumpet' },
  { value: 'trombone', label: '58. Trombone' },
  { value: 'tuba', label: '59. Tuba' },
  { value: 'muted_trumpet', label: '60. Muted Trumpet' },
  { value: 'french_horn', label: '61. French Horn' },
  { value: 'brass_section', label: '62. Brass Section' },
  { value: 'synth_brass_1', label: '63. SynthBrass 1' },
  { value: 'synth_brass_2', label: '64. SynthBrass 2' },
  { value: 'soprano_sax', label: '65. Soprano Sax' },
  { value: 'alto_sax', label: '66. Alto Sax' },
  { value: 'tenor_sax', label: '67. Tenor Sax' },
  { value: 'baritone_sax', label: '68. Baritone Sax' },
  { value: 'oboe', label: '69. Oboe' },
  { value: 'english_horn', label: '70. English Horn' },
  { value: 'bassoon', label: '71. Bassoon' },
  { value: 'clarinet', label: '72. Clarinet' },
  { value: 'piccolo', label: '73. Piccolo' },
  { value: 'flute', label: '74. Flute' },
  { value: 'recorder', label: '75. Recorder' },
  { value: 'pan_flute', label: '76. Pan Flute' },
  { value: 'blown_bottle', label: '77. Blown Bottle' },
  { value: 'shakuhachi', label: '78. Shakuhachi' },
  { value: 'whistle', label: '79. Whistle' },
  { value: 'ocarina', label: '80. Ocarina' },
  { value: 'lead_1_square', label: '81. Lead 1 (square)' },
  { value: 'lead_2_sawtooth', label: '82. Lead 2 (sawtooth)' },
  { value: 'lead_3_calliope', label: '83. Lead 3 (calliope)' },
  { value: 'lead_4_chiff', label: '84. Lead 4 (chiff)' },
  { value: 'lead_5_charang', label: '85. Lead 5 (charang)' },
  { value: 'lead_6_voice', label: '86. Lead 6 (voice)' },
  { value: 'lead_7_fifths', label: '87. Lead 7 (fifths)' },
  { value: 'lead_8_bass__lead', label: '88. Lead 8 (bass + lead)' },
  { value: 'pad_1_new_age', label: '89. Pad 1 (new age)' },
  { value: 'pad_2_warm', label: '90. Pad 2 (warm)' },
  { value: 'pad_3_polysynth', label: '91. Pad 3 (polysynth)' },
  { value: 'pad_4_choir', label: '92. Pad 4 (choir)' },
  { value: 'pad_5_bowed', label: '93. Pad 5 (bowed)' },
  { value: 'pad_6_metallic', label: '94. Pad 6 (metallic)' },
  { value: 'pad_7_halo', label: '95. Pad 7 (halo)' },
  { value: 'pad_8_sweep', label: '96. Pad 8 (sweep)' },
  { value: 'fx_1_rain', label: '97. FX 1 (rain)' },
  { value: 'fx_2_soundtrack', label: '98. FX 2 (soundtrack)' },
  { value: 'fx_3_crystal', label: '99. FX 3 (crystal)' },
  { value: 'fx_4_atmosphere', label: '100. FX 4 (atmosphere)' },
  { value: 'fx_5_brightness', label: '101. FX 5 (brightness)' },
  { value: 'fx_6_goblins', label: '102. FX 6 (goblins)' },
  { value: 'fx_7_echoes', label: '103. FX 7 (echoes)' },
  { value: 'fx_8_scifi', label: '104. FX 8 (sci-fi)' },
  { value: 'sitar', label: '105. Sitar' },
  { value: 'banjo', label: '106. Banjo' },
  { value: 'shamisen', label: '107. Shamisen' },
  { value: 'koto', label: '108. Koto' },
  { value: 'kalimba', label: '109. Kalimba' },
  { value: 'bagpipe', label: '110. Bagpipe' },
  { value: 'fiddle', label: '111. Fiddle' },
  { value: 'shanai', label: '112. Shanai' },
  { value: 'tinkle_bell', label: '113. Tinkle Bell' },
  { value: 'agogo', label: '114. Agogo' },
  { value: 'steel_drums', label: '115. Steel Drums' },
  { value: 'woodblock', label: '116. Woodblock' },
  { value: 'taiko_drum', label: '117. Taiko Drum' },
  { value: 'melodic_tom', label: '118. Melodic Tom' },
  { value: 'synth_drum', label: '119. Synth Drum' },
  { value: 'reverse_cymbal', label: '120. Reverse Cymbal' },
  { value: 'guitar_fret_noise', label: '121. Guitar Fret Noise' },
  { value: 'breath_noise', label: '122. Breath Noise' },
  { value: 'seashore', label: '123. Seashore' },
  { value: 'bird_tweet', label: '124. Bird Tweet' },
  { value: 'telephone_ring', label: '125. Telephone Ring' },
  { value: 'helicopter', label: '126. Helicopter' },
  { value: 'applause', label: '127. Applause' },
  { value: 'gunshot', label: '128. Gunshot' }
];